#!/bin/sh

if [ -z "$(which ncmpcpp)" ]; then
  echo Need to install ncmpcpp.
  exit 1
fi

mkdir ~/.config/ 2>/dev/null
unlink "$HOME/.config/ncmpcpp" 2>/dev/null
ln -sf "$PWD" "$HOME/.config/ncmpcpp"

