# Typical laptop setup, with wifi, brightness, battery etc, for

# fonts we'll be re-using here and there
awesome: &awesome Font Awesome 6 Free:style=solid:pixelsize=14
awesome_brands: &awesome_brands Font Awesome 6 Brands:pixelsize=16
julia: &julia JuliaMono:pixelsize=16
underline_color: &underline_color a59fb5ff
bg_highlight: &bg_highlight 8f82b5cc
bg_default: &bg_default {stack: [{background: {color: *bg_highlight}}, {underline: {size: 4, color: *underline_color}}]}
fg_alt: &fg_alt 7963b5ff
fg_crit: &fg_crit ff0000ff
fg_warn: &fg_warn ffa600ff
fg_info: &fg_ok 0000ffff
fg_ok: &fg_ok 00ff00ff
fg_sub: &fg_sub ffffff66

std_underline: &std_underline {underline: { size: 2, color: *underline_color}}

# This is THE bar configuration
bar:
  height: 35
  location: top
  spacing: 5
  margin: 7

  # Default font
  font: *julia

  foreground: ffffffff
  background: 111111cc

  border:
    width: 1
    color: 999999cc
    margin: 5
    top-margin: 0

  left:
    - river:
        anchors:
          - base: &river_base
              left-margin: 10
              right-margin: 13
              default: {string: {text: , font: *julia}}
              conditions:
                id == 1: {string: {text: 1, font: *julia}}
                id == 2: {string: {text: 2, font: *julia}}
                id == 3: {string: {text: 3, font: *julia}}
                id == 4: {string: {text: 4, font: *julia}}
                id == 5: {string: {text: 5, font: *julia}}
                id == 6: {string: {text: 6, font: *julia}}
                id == 7: {string: {text: 7, font: *julia}}
                id == 8: {string: {text: 8, font: *julia}}
                id == 9: {string: {text: 9, font: *julia}}
                id == 10: {string: {text: "scratchpad", font: *julia}}
                id == 11: {string: {text: "work", font: *julia}}

        content:
          map:
            on-click:
              left: sh -c "riverctl set-focused-tags $((1 << ({id} - 1)))"
              right: sh -c "riverctl toggle-focused-tags $((1 << ({id} -1)))"
              middle: sh -c "riverctl toggle-view-tags $((1 << ({id} -1)))"
            conditions:
              state == urgent:
                map:
                  <<: *river_base
                  deco: {background: {color: *bg_highlight}}
              state == focused:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == visible && ~occupied:
                map:
                  <<: *river_base
              state == visible && occupied:
                map:
                  <<: *river_base
                  deco: *bg_default
              state == unfocused:
                map:
                  <<: *river_base
              state == invisible && ~occupied: {empty: {}}
              state == invisible && occupied:
                map:
                  <<: *river_base
                  deco: {underline: {size: 3, color: *underline_color}}

    - foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{app-id}", foreground: *fg_alt}
                - string: {text: ": {title}"}

  center:
    - mpd:
        host: /run/user/1000/mpd/socket
        anchors:
          list: &artist_album_title
            spacing: 0
            items:
              - map:
                  conditions:
                    state == playing: {string: {text: "{artist}"}}
                    state == paused: {string: {text: "{artist}", foreground: *fg_sub}}
              - string: {text: " | ", foreground: *fg_sub}
              - map:
                  conditions:
                    state == playing: {string: {text: "{album}"}}
                    state == paused: {string: {text: "{album}", foreground: *fg_sub}}
              - string: {text: " | ", foreground: *fg_sub}
              - map:
                  conditions:
                    state == playing: {string: {text: "{title}", foreground: *fg_alt}}
                    state == paused: {string: {text: "{title}", foreground: *fg_sub}}

        content:
          map:
            margin: 10
            conditions:
              state == offline: {string: {text: offline, foreground: *fg_crit}}
              state == stopped: {string: {text: stopped}}
              state == paused: {list: *artist_album_title}
              state == playing: {list: *artist_album_title}

  right:
    - cpu:
        poll-interval: 2500
        content:
          map:
            conditions:
              id < 0:
                - string: {text: cpu, font: *julia}
                - string: {text: "{cpu}%"}
    - mem:
        poll-interval: 2500
        content:
          string: {text: "{used:mb}MB"}
    - script:
        path: ~/.config/yambar/scripts/temps.sh
        args: []
        content:
          string:
            margin: 1
            text: "{cputemp} {gputemp}"
            font: *julia
    - script:
        path: ~/.config/yambar/scripts/wttr-poll.sh
        args: []
        content:
          string: 
            margin: 0
            text: "{wttr}"
            font: *julia

    - removables:
        anchors:
          drive: &drive { text: , font: *awesome}
          optical: &optical {text: , font: *awesome}
        spacing: 5
        content:
          map:
            conditions:
              ~mounted:
                map:
                  on-click: udisksctl mount -b {device}
                  conditions:
                    ~optical: [{string: *drive}, {string: {text: "{label}"}}]
                    optical: [{string: *optical}, {string: {text: "{label}"}}]
              mounted:
                map:
                  on-click: udisksctl unmount -b {device}
                  conditions:
                    ~optical:
                      - string: {<<: *drive, deco: *std_underline}
                      - string: {text: "{label}"}
                    optical:
                      - string: {<<: *optical, deco: *std_underline}
                      - string: {text: "{label}"}
    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == eth0:
                map:
                  conditions:
                    ~carrier: {empty: {}}
                    carrier:
                      map:
                        default: {string: {text: , font: *awesome, foreground: *fg_sub}}
                        conditions:
                          state == up && ipv4 != "":
                            - string: {text: , font: *awesome}
                            - string: {text: "{dl-speed:mb}/{ul-speed:mb} Mb/s"}
              name == enp5s0:
                map:
                  conditions:
                    ~carrier: {empty: {}}
                    carrier:
                      map:
                        default: {string: {text: , font: *awesome, foreground: *fg_sub}}
                        conditions:
                          state == up && ipv4 != "":
                            - string: {text: , font: *awesome}
                            - string: {text: "{dl-speed:mb}/{ul-speed:mb} Mb/s"}
    - network:
        poll-interval: 1000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlan0:
                map:
                  default: {string: {text: , font: *awesome, foreground: *fg_sub}}
                  conditions:
                    state == down: {string: {text: , font: *awesome, foreground: *fg_crit}}
                    state == up:
                      map:
                        default:
                          - string: {text: , font: *awesome}
                          - string: {text: "{ssid} {dl-speed:mb}/{ul-speed:mb} Mb/s"}

                        conditions:
                          ipv4 == "":
                            - string: {text: , font: *awesome, foreground: *fg_sub}
                            - string: {text: "{ssid} {dl-speed:mb}/{ul-speed:mb} Mb/s", foreground: *fg_sub}

    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted:
                string:
                  text: "0%"
                  on-click:
                    middle: sh -c "amixer set Master 1+ toggle"
              ~muted:
                string:
                  text: "{cubic_volume}%"
                  on-click:
                    middle: sh -c "amixer set Master 1+ toggle"
                    wheel-down: sh -c "amixer sset Master 2%-"
                    wheel-up: sh -c "amixer sset Master 2%+"
        content:
          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          icon == "audio-headset-bluetooth":
                            string: {text: "󰋋", font: *awesome}
                          muted: {string: {text: "󰝟", font: *awesome}}
                        default:
                          - ramp:
                              tag: cubic_volume
                              items:
                                - string: {text: "󰕿", font: *awesome}
                                - string: {text: "󰖀", font: *awesome}
                                - string: {text: "󰕾", font: *awesome}
                    type == "source":
                      - string: {text: "", font: *awesome, left-margin: 5}
              - map:
                  <<: *volume
    - clock:
        time-format: "%H:%M %Z"
        content:
          - string: {text: , font: *awesome}
          - string: {text: "{date}", right-margin: 5}
          - string: {text: , font: *awesome}
          - string: {text: "{time}"}
    - label:
        content:
          string:
            on-click: systemctl poweroff
            text: 
            font: *awesome
