
if which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS"]; then
  eval `dbus-lauch --sh-syntax --exit-with-session`
fi

unset XDG_RUNTIME_DIR
export XDG_RUNTIME_DIR=$HOME/.local/run
mkdir $XDG_RUNTIME_DIR

unset XDG_SESSION_TYPE
export XDG_SESSION_TYPE=tty

pipewire &
pipewire-pulse &
pipewire-media-session &
pipewire -c ~/.config/pipewire/filter-chain/input-filter-chain.conf &
#pulseaudio -D

session=${1:-dwm}
case $session in
    dwm          ) baraction.sh 1>/dev/null 2>&1 & exec dbus-run-session -- dwm;;
    i3|i3wm      ) exec dbus-run-session -- i3;;
    spectrwm     ) exec dbus-run-session -- spectrwm;;
    # No known session, try to run it as command
    *            ) exec $1;;
esac

