
#export XDG_RUNTIME_DIR=$HOME/.local/run
#pipewire &
#pipewire-pulse &
#pipewire-media-session &
session=${1:-dwm}

case $session in
    dwm          ) baraction.sh 2>1 1>/dev/null & exec dbus-run-session -- dwm;;
    i3|i3wm      ) exec dbus-run-session -- i3;;
    spectrwm     ) exec dbus-run-session -- spectrwm;;
    # No known session, try to run it as command
    *            ) exec $1;;
esac

