
if [ which dbus-launch >/dev/null && test -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
  eval `dbus-launch --sh-syntax --exit-with-session`
fi

unset XDG_RUNTIME_DIR
export XDG_RUNTIME_DIR=/run/user/$(id -u)
mkdir $XDG_RUNTIME_DIR

unset XDG_SESSION_TYPE
export XDG_SESSION_TYPE=tty

while :; do wttr format="%l:+%C+%t\n" > /tmp/wttr; sleep 1800; done &

~/.xstartup

session=${1:-dwm}
case $session in
    dwm          ) baraction.sh 1>/dev/null 2>&1 & exec dbus-run-session -- dwm;;
    i3|i3wm      ) exec dbus-run-session -- i3;;
    spectrwm     ) exec dbus-run-session -- spectrwm;;
    stumpwm      ) exec dbus-run-session -- /home/chris/repos/github/stumpwm/stumpwm/stumpwm;;
    # No known session, try to run it as command
    *            ) exec $1;;
esac

