#!/bin/bash

if [[ "$@" =~ ^([1-2]?[[:space:]]?[[:alpha:][:space:]]+)[[:space:]]([0-9]{1,3}):?([0-9]{1,3})?-?([0-9]{1,3})?[[:space:]]?([[:alpha:]]{3,5})? ]]; then
  book="${BASH_REMATCH[1]}"
  chapter="${BASH_REMATCH[2]}"
  verse1="${BASH_REMATCH[3]}"
  verse2="${BASH_REMATCH[4]}"
  ver="${BASH_REMATCH[5]}"
fi

#echo $book
#echo $chapter
#echo $verse1
#echo $verse2
#echo $ver

case ${ver,,} in
  "esv") bibget.esvapi $@ ;;
  *)  bibget.bibleapi $@ ;;
esac

