#!/bin/bash

if [ $# -lt 2 ]; then
  echo "usage: $0 <src_folder> <dest_folder>"
  exit 1
fi

in_folder=$1
out_folder="$2/$(basename $in_folder)"
mkdir -p "$out_folder"
for file in $(find "$in_folder" -name *.flac); do
  name=$(basename $file .flac)
  echo "copying $file to $out_folder/$name.mp3"

  ffmpeg -i "$file" -ab 320k -map_metadata 0 -id3v2_version 3 "$out_folder/$name.mp3"
done
for file in $(find "$in_folder" -name *.mp3); do
  echo "copying $in_folder/$file to $out_folder/$file"
  cp "$file" "$out_folder/"
done
