#!/bin/sh

if [ ! $ZET_DIR ]; then
  echo "ZET_DIR not defined"
  exit 1
fi
newEntry=$(date +%Y%m%d%H%M%S)
echo $newEntry
if [ ! -d $ZET_DIR ]; then
  echo "ZET_DIR: '$ZET_DIR' doesn't exist"
  exit 1
fi
cd $ZET_DIR/
mkdir -p $newEntry 2>/dev/null
cd $newEntry
if [ ! -e README.md ]; then
  touch README.md
fi
exec vim + README.md
