#!/bin/sh

if [ -z "$(which pipewire)" ]; then
  echo Need to install pipewire.
  exit 1
fi

mkdir ~/.config/ 2>/dev/null
unlink "$HOME/.config/pipewire" 2>/dev/null
ln -sf "$PWD" "$HOME/.config/pipewire"

